version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    deploy:
      resources:
        limits:
          memory: 8G

  rag-qa-api:
    build: .
    ports:
      - "8098:8000"
    volumes:
      - ./chroma_db:/app/chroma_db
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  ollama_data: